export enum Subject {
  MATH = "MATEMATYKA",
  PHYSICS = "FIZYKA",
  PROGRAMING = "PROGRAMOWANIE",
  ALGORITHMS_AND_DATA_STRUCTURES = "ALGORYTMY I STRUKTURY DANYCH",
  NETWORK_SECURITY = "BEZPIECZEŃSTWO SIECI",
  MACHINE_LEARNING = "UCZENIE MASZYNOWE",
  OTHER = "INNE"
}
