name: Deploy frontend

on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker build -t krzysztofkulacz/classconect-frontend:latest .
          docker push krzysztofkulacz/classconect-frontend:latest

      - name: SSH into VPS and update container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/debian/docker_data/classconnect/docker-compose/v1
            docker-compose stop classconect-frontend
            docker-compose rm -f  classconect-frontend
            docker system prune -f -a --volumes
           
