name: Deploy frontend

on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#       - name: Build and push Docker Image
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         run: |
#           docker build -t krzysztofkulacz/classconect-frontend:latest .
#           echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
#           docker push krzysztofkulacz/classconect-frontend:latest
      - name: SSH into VPS and update container
        env:
          VPS_IP: ${{secrets.VPS_IP}}
          VPS_USERNAME: ${{secrets.VPS_USERNAME}}
          VPS_KEY: ${{secrets.VPS_KEY}}
        uses: appleboy/ssh-action@v0.3.0
        with:
          host: your-vps-ip
          username: your-vps-username
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /home/debian/docker_data/classconnect/docker-compose/v1
            mkdir testssh
